In [99]:
import numpy as np

a = np.arange(15).reshape(3, 5)

print(f'数组维度：{a.shape}')
print(f'数组轴个数：{a.ndim}')
print(f'数组元素类型：{a.dtype}')
print(f'数组中每个元素的字节大小：{a.itemsize}')
print(f'数组中元素总个数：{a.size}')
print(f'类型查询：{type(a)}')

# 创建一个数组
b = np.array([6, 7, 8])
print(f'数组：{b}')
print(f'数组类型：{type(b)}')

数组维度：(3, 5)
数组轴个数：2
数组元素类型：int64
数组中每个元素的字节大小：8
数组中元素总个数：15
类型查询：<class 'numpy.ndarray'>
数组：[6 7 8]
数组类型：<class 'numpy.ndarray'>


In [ ]:
import numpy as np

a = np.array([2, 3, 4])
print(f'数组元素类型:{a}')
print(f'数组类型:{a.dtype}')


b = np.array([1.2, 3.5, 5.1])
print(f'数组元素类型:{b.dtype}')

In [ ]:
import numpy as np

# 测试zeros()、ones()、empty()函数
zero = np.zeros((3, 4))
print(f'创建zero数组:{zero}')

one = np.ones((2, 3, 4))
print(f'创建one数组:{one}')

empty = np.empty((2, 3))
print(f'创建empty数组:{empty}')


# arange() 函数测试
> arange()类似于python中的range() 创建一个一维ndarray数组

In [ ]:
import numpy as np

arange = np.arange(10, 20, 5, dtype=int)
print(f'arange创建的数组{arange}')
print(f'arange创建的元素类型:{arange.dtype}')
print(f'arange创建的类型:{type(arange)}')


# matrix() 函数测试
> matrix是ndarray的子类，只能创建二维矩阵

In [ ]:
import numpy as py

mat = np.mat('1 2;3 4')
print(f'mat:{mat}')

matrix = np.matrix('1,2;3,4')
print(f'matrix:{matrix}')


# random()函数
> 创建随机矩阵

In [ ]:
import numpy as np

# 创建3行4列的矩阵，并且数据类型为浮点数
random = np.random.rand(3, 4)
print(f'随机矩阵:{random}')
print(f'随机矩阵类型:{type(random)}')

# 创建3行4列随机二维整形数组，指定数据为-1 ～5
randomInt = np.random.randint(-1, 5, size=(3, 4))
print(f'随机矩阵:{randomInt}')
print(f'随机矩阵类型:{type(randomInt)}')

# 创建3行4列随机二维整形数组，指定数据为-1 ～5均匀样本值
randomUniform = np.random.uniform(-1, 5, size=(3, 4))
print(f'随机矩阵:{randomUniform}')
print(f'随机矩阵类型:{type(randomUniform)}')


# ndarray的数据类型
> 1、dtype参数，指定数组的数据类型，类型名+位数，如float64，int32

> 2、astype方法，转换数组的数据类型

In [ ]:
import numpy as np

# 初始化一个一个三行四列的数组，类型为float64、int32
zeros_float_arr = np.zeros((3, 4), dtype=np.float64)
print(f'zeros_float_arr:{zeros_float_arr}')
print(f'zeros_float_arr类型:{zeros_float_arr.dtype}')

# 将已有的数组数据类型转换为int32
zeros_int_arr = zeros_float_arr.astype(np.int32)
print(f'zeros_int_arr:{zeros_int_arr}')
print(f'zeros_int_arr类型：{zeros_int_arr.dtype}')


# 等比/等差数列
1、np.logspace()等比数列 np.logspace('开始点', '结束点', '元素个数')

2、np.linspace()等差数列

In [ ]:
import numpy as np

# 创建一个开始点为0，结束点为0，长度为10
gp1 = np.logspace(0 ,0 ,10)
print(f'等比数列-1:{gp1}')

# 创建一个开始点为0，结束点为9，长度为10
gp2 = np.logspace(0, 9, 10)
print(f'等比数列-2:{gp2}')

# 创建一个开始点为0，结束点为9， 长度为10，底数为2
gp3 = np.logspace(0, 9, 10, base=2)
print(f'等比数列-3:{gp3}')

# 创建一个开始点为1，结束点9，长度为10
ap = np.linspace(1, 9, 10)
print(f'等差数列-1:{ap}')

# 创建一个开始点0， 结束点9，长度为10
ap2 = np.linspace(0, 9, 10)
print(f'等差数列-2：{ap2}')

# 创建一个开始点1，结束点10，长度为10， 包含终止值
ap3 = np.linspace(1, 10, 10, endpoint=False)
print(f'等差数列-3：{ap3}')


# NnmPy内置函数

In [ ]:
import numpy as np

# 创建一个具有标准正态分布的序列
arr = np.random.randn(2, 3)
print(f'随机序列:{arr}')

print(f'随机序列向上取整:{np.ceil(arr)}')
print(f'随机序列向下取整:{np.floor(arr)}')
print(f'随机序列四舍五入:{np.rint(arr)}')
print(f'随机序列元素是否为空:{np.isnan(arr)}')
print(f'随机序列元素相乘:{np.multiply(arr, arr)}')
print(f'随机序列元素相除:{np.divide(arr, arr)}')
print(f'随机序列元素绝对值:{np.abs(arr)}')
print(f'随机序列元素判断:{np.where(arr > 1, 1, -1)}')


# 统计函数

In [ ]:
import numpy as np

# 生成一个元素不大于12的3x4的等差数列
arr = np.arange(16).reshape(4, 4)

print(f'等差数列:{arr}')
print(f'等差数列元素平均值:{np.mean(arr)}')
print(f'等差数列元素和:{np.sum(arr, axis = 0)}')
print(f'等差数列元素和:{np.sum(arr, axis = 1)}')
print(f'等差数列元素最大值:{np.max(arr)}')
print(f'等差数列元素最小值:{np.min(arr)}')
print(f'等差数列元素标准差:{np.std(arr)}')
print(f'等差数列元素方差:{np.var(arr)}')
print(f'等差数列最大值下标索引:{np.argmax(arr)}')
print(f'等差数列最小值下标索引:{np.argmin(arr)}')
print(f'等差数列元素累加和:{np.cumsum(arr)}')
print(f'等差数列元素累计乘积:{np.cumprod(arr)}')

# 比较函数

In [74]:
import numpy as np

# 创建一个具有正态分布的标准序列
arr = np.random.randn(2, 3)
print(f'序列:{arr}')

print(f'序列至少有一个满足：{np.any(arr > 0)}')
print(f'序列所有元素均满足：{np.all(arr > 0)}')

序列:[[-1.20727814 -1.24072031  1.21447985]
 [ 1.43832624  0.57884549  1.63242508]]
序列至少有一个满足：True
序列所有元素均满足：False


# 去重函数

In [80]:
import numpy as np

# 创建一个数组
arr = np.array([[1, 2, 1], [2, 4, 2]])
print(f'数组:{arr}')

print(f'数组去重:{np.unique(arr)}')


数组:[[1 2 1]
 [2 4 2]]
数组去重:[1 2 4]


# 排序函数

In [85]:
import numpy as np

# 创建一个数组
arr = np.array([1, 2, 34, 5])
print(f'数组：{arr}')

print(f'数组排序：{arr.sort()}')
print(f'数组排序：{np.sort(arr)}')


数组：[ 1  2 34  5]
数组排序：None
数组排序：[ 1  2  5 34]


# Numpy运算

## 1、数组运算

In [91]:
import numpy as np

# 创建一个固定数组
arr1 = np.array([20, 30, 40, 50])
print(f'固定数组：{arr}')

# 生成一个从0到4的随机数组
arr2 = np.arange(4)
print(f'随机数组：{arr2}')

# 数组相减
print(f'数组相减：{arr1 - arr2}')

# 数组相加
print(f'数组相加：{arr1 + arr2}')

# 数组相乘
print(f'数组相乘：{arr1 * arr2}')


固定数组：[ 1  2  5 34]
随机数组：[0 1 2 3]
数组相减：[20 29 38 47]
数组相加：[20 31 42 53]
数组相乘：[  0  30  80 150]


## 2、矩阵乘法

In [98]:
import numpy as np

# 创建一个固定数组
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
print(f'数组1:{arr}')

# 创建一个固定数组
arr2 = np.array([[6, 23], [-1, 7], [8, 9]])
print(f'数组2:{arr2}')

# 矩阵元素相乘
print(f'矩阵相乘：{np.dot(arr1, arr2)}')
print(f'矩阵相乘：{arr1.dot(arr2)}')

# 矩阵元素相乘
arr3 = np.array([[1, 2, 3], [4, 5, 6]])
print(f'arr3:{arr3}')

arr4 = np.array([[2, 2, 2], [3, 3, 3]])
print(f'arr4:{arr4}')

print(f'矩阵元素相乘:{arr3 * arr4}')



数组1:[ 1  2  5 34]
数组2:[[ 6 23]
 [-1  7]
 [ 8  9]]
矩阵相乘：[[ 28  64]
 [ 67 181]]
矩阵相乘：[[ 28  64]
 [ 67 181]]
arr3:[[1 2 3]
 [4 5 6]]
arr4:[[2 2 2]
 [3 3 3]]
矩阵元素相乘:[[ 2  4  6]
 [12 15 18]]
