# 学习目标：
- 知道什么是深度学习



# 1、什么是深度学习？
概念：深度学习（Deep Learning）是机器学习的分支，是一种以人工神经网络为架构，对数据进行特征学的算法，而“深度”是指网络中使用多层结构
核心：深度学习是通过模仿人脑中神经网络来处理和分析复杂的数据，从大量数据中自动提取复杂特征，擅长处理高纬数据，如图像、语音和文本


# 2、深度学习的发展历程？

![神经网络和深度学习发展史](./file/神经网络和深度学习发展史.png)

- 早期探索：20世纪40年代McCulloch-Pitts神经元、1958年弗兰克·罗森布拉特（Frank Rosenblatt）提出感知器概念、1960年多层感知器（MLP）提出
- 挑战与瓶颈：1986年反向传播算法（Backpropagation）提出，使得多层神经网络（即深层网络）能够通过梯度下降优化参数，解决复杂的非线性问题；支持向量机（SVM）提出
- 复兴与突破：2006年深度信念网络（DBN）、2012年深度学习概念提出并使用了卷积神经网络、2014年：生成对抗网络（GANs）提出；2015年：ResNet（残差网络）由何凯明（Kaiming He）提出
- 爆发期：2016年Google AlphaGo（Deep Reinforcement Learning） 战胜李世石（人工智能第三次浪潮）；2017年自然语言处理NLP的Transformer框架出现；2018年BERT和GPT的出现；2022年ChatGPT的出现，进入到大模型AIGC发展的阶段

# 3、深度学习有哪些特点？
- 多层非线性变换：深度学习模型由多个层次组成，每层都应用非线性激活函数对输入数据进行变换，较低的层级通常捕捉到简单的特征（如边缘、色彩），而更高的层级则可以识别更复杂的模式
- 自动特征提取：与传统的机器学习算法不同，深度学习能够自动从原始数据中学习到更有用的特征，而不需要人工特征工程，使得深度学习在许多领域中表现出色
- 大数据和计算能力：深度学习模型通常需要大量的标注数据和强大的计算资源（如GPU）来进行训练，大数据和高性能计算使得深度学习在图像识别、自然语言处理等领域取得了显著的突破
- 可解释性差：深度学习模型内部的运行机制相对不透明，被称为“黑箱”，这意味着理解模型为什么做出特定的决策可能比较困难，这对某些应用场景来说是一个挑战。

# 4、常见的深度学习模型有哪些？
- 卷积神经网络（CNN）：
- 循环神经网络（RNN）：
- 自编码器（AutoEncoders）：
- 生成对抗网络（GAN）：
- Transformer：

# 5、深度学习有哪些应用场景？
- 计算机视觉（Computer Vision）：图像分类、目标检测、面部识别、图像生成
- 自然语言处理（NLP）：机器翻译、情感分析、文本生成、语音识别、聊天机器人
- 推荐系统（Recommendation Systems）：电影/音乐推荐、电商推荐、社交媒体推荐






In [2]:
!pip install torch -i https://pypi.tuna.tsinghua.edu.cn/simple

Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 150.8/150.8 MB 2.5 MB/s eta 0:00:0000:0100:02
Note: you may need to restart the kernel to use updated packages.


In [11]:
import torch  # 需要安装torch模块
import numpy as np

# torch.tensor(data=, dtype=) 根据指定数据创建张量
# 1.创建张量标量（data=, dtype=）
data = torch.tensor(10)
print(data)

# 2.numpy数组，犹豫data为float64，张量元素类型也是float64
data = np.random.randn(2, 3)
data = torch.tensor(data)
print(data)

# 3.列表、浮点数默认都是flaot32
data = [[10, 20, 30], [40, 50, 60]]
data = torch.tensor(data)
print(data)

tensor(10)
tensor([[-1.3145,  0.0305,  0.2641],
        [ 1.7537, -1.6119,  0.5571]])
tensor([[10, 20, 30],
        [40, 50, 60]])


In [10]:
# torch.Tensor(size=) 根据形状来创建张量
# 1、创建一个2行3列的张量，默认dtype为float32
data = torch.Tensor(2, 3)
print(data)

# 2、如果传递列表代表，则包含创建包含指定元素的张量
data = torch.Tensor([10])
print(data)

data = torch.Tensor([10, 20])
print(data)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([10.])
tensor([10., 20.])


In [15]:
# torch.IntTensor()/torch.FloatTensor() 创建指定类型的张量

# 1、创建2行3列，dtype为int32的张量
data = torch.IntTensor(2, 3)
print(f'2行3列，dtype为int32的张量：{data}')

# 2、如果传入的元素类型不正确，则回进行类型转换
#data = torch.IntTensor([2.5, 3.3])
#print(f'类型转换张量：{data}')

# 3、其他类型
data = torch.ShortTensor()  # int16
print(f'int16类型张量：{data}')

data = torch.LongTensor()  # int64
print(f'int64类型张量：{data}')

data = torch.FloatTensor()  # float32
print(f'float32类型张量：{data}')

data = torch.DoubleTensor()  # float64
print(f'float64类型张量：{data}')

2行3列，dtype为int32的张量：tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)
int16类型张量：tensor([], dtype=torch.int16)
int64类型张量：tensor([], dtype=torch.int64)
float32类型张量：tensor([])
float64类型张量：tensor([], dtype=torch.float64)


In [17]:
# 线性和随机张量

# torch.arange(start=, end=, step=)：固定步长线性张量
# 1、在指定区间按照补偿生成元素[start, end, steps]左闭右开
data = torch.arange(0, 10, 2)
print(data)

# 2、在指定区间啊找元素个数生成[start, end, steps]左闭右闭
# step = (end - start) /( step - 1)
# value_i = start + step * i
data = torch.linspace(0, 9, 10)
print(data)

tensor([0, 2, 4, 6, 8])
tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])


In [18]:
# torch.randn/rand(size=) 创建随机浮点数类型张量
# torch.randint(low=, high=, size=) 创建随机整数类型张量 左闭右开
# torch.initial_seed() 和 torch.manual_seed(seed=) 随机种子设置

# 1、创建随机张量
data = torch.randn(2, 3)
print(data)
print(f'查看随机数种子：{torch.initial_seed()}')

# 2、随机数种子设置
torch.manual_seed(100)
data = torch.randn(2, 3)
print(data)
print(f'随机数种子：{torch.initial_seed()}')



tensor([[-1.3907, -0.3289, -0.9731],
        [-1.6339,  0.1636, -0.1399]])
查看随机数种子：14091556506313435554
tensor([[ 0.3607, -0.2859, -0.3938],
        [ 0.2429, -1.3833, -2.3134]])
随机数种子：100


In [21]:
# 指定值张量

# torch.zeros(size=) 和 torch.zeros_like(input=) 创建全0张量
# 1、创建指定形状全0张量
data = torch.zeros(2, 3)
print(f'创建指定形状全零张量:{data}')

# 2、根据张量形状创建全0张量
data = torch.zeros_like(data)
print(f'根据传入张量形状创建全零张量：{data}')

# torch.ones(size=) 和 torch.ones_like(input=) 创建全1张量
# 3、创建指定形状全1张量
data = torch.ones(2, 3)
print(f'指定形状全一张量：{data}')

data = torch.ones_like(data)
print(f'根据输入张量形状创建全一张量：{data}')

# torch.full(size=, fill_value=) 和 torch.full_like(input=, fill_value=) 创建全为指定值张量
# 4、 创建指定形状指定值的张量
data = torch.full([2, 3], 10)
print(f'全为指定值张量:{data}')

# 5、根据张量形状创建指定值的张量
data = torch.full_like(data, 20)
print(f'根据张量形状创建指定值的张量:{data}')


创建指定形状全零张量:tensor([[0., 0., 0.],
        [0., 0., 0.]])
根据传入张量形状创建全零张量：tensor([[0., 0., 0.],
        [0., 0., 0.]])
指定形状全一张量：tensor([[1., 1., 1.],
        [1., 1., 1.]])
根据输入张量形状创建全一张量：tensor([[1., 1., 1.],
        [1., 1., 1.]])
全为指定值张量:tensor([[10, 10, 10],
        [10, 10, 10]])
根据张量形状创建指定值的张量:tensor([[20, 20, 20],
        [20, 20, 20]])


In [24]:
# 指定元素类型张量
# data.type(dtype=)
data = torch.full([2, 3], 10)
print(data.dtype)

# 将 data 元素类型转换为 float64 类型
data = data.type(torch.DoubleTensor)
print(data.dtype)

# 转换为其他类型
data = data.type(torch.ShortTensor)
data = data.type(torch.IntTensor)
data = data.type(torch.LongTensor)
data = data.type(torch.FloatTensor)
data = data.type(dtype=torch.float16)

# data.half/float/double/short/int/long()
data = torch.full([2, 3], 10)
print(data.dtype)
# 将 data 元素类型转换为 float64 类型
data = data.double()
print(data.dtype)
# 转换为其他类型
# data = data.short()
# data = data.int()
# data = data.long()
# data = data.float()


torch.int64
torch.float64
torch.int64
torch.float64


In [26]:
# 张量类型转换

# 使用 t.numpy() 函数可以将张量转换为 ndarray 数组，但是共享内存，可以使用copy函数避免共享。

# 1、张量转换为NumPy数组
data_tensor = torch.tensor([2, 3, 4])
# 使用张量对象中的 numpy 函数进行转换
data_numpy = data_tensor.numpy()
print(type(data_tensor))
print(type(data_numpy))
# 注意: data_tensor 和 data_numpy 共享内存
# 修改其中的一个，另外一个也会发生改变
# data_tensor[0] = 100
data_numpy[0] = 100
print(data_tensor)
print(data_numpy)

# 2. 对象拷贝避免共享内存
data_tensor = torch.tensor([2, 3, 4])
# 使用张量对象中的 numpy 函数进行转换，通过copy方法拷贝对象
data_numpy = data_tensor.numpy().copy()
print(type(data_tensor))
print(type(data_numpy))
# 注意: data_tensor 和 data_numpy 此时不共享内存
# 修改其中的一个，另外一个不会发生改变
# data_tensor[0] = 100
data_numpy[0] = 100
print(data_tensor)
print(data_numpy)


RuntimeError: Numpy is not available

In [29]:
# 当张量只包含一个元素时, 可以通过 item() 函数提取出该值
data = torch.tensor([30, ])
print(data.item())
data = torch.tensor(30)
print(data.item())

30
30


In [33]:
data = torch.randint(0, 10, [2, 3])
print(f'初始化张量:{data}')

# 1. 不修改原数据
new_data = data.add(10)  # 等价 new_data = data + 10
print(f'张量+10:{data}')

# 2. 直接修改原数据 注意: 带下划线的函数为修改原数据本身
data.add_(10)
print(f'张量再+10:{data}')

# 3. 其他函数
print(f'张量减100:{data.sub(100)}')
print(f'张量乘100:{data.mul(100)}')
print(f'张量除100:{data.div(100)}')
print(f'张量除100:{data.neg()}')

初始化张量:tensor([[7, 0, 0],
        [9, 5, 7]])
张量+10:tensor([[7, 0, 0],
        [9, 5, 7]])
张量再+10:tensor([[17, 10, 10],
        [19, 15, 17]])
张量减100:tensor([[-83, -90, -90],
        [-81, -85, -83]])
张量乘100:tensor([[1700, 1000, 1000],
        [1900, 1500, 1700]])
张量除100:tensor([[0.1700, 0.1000, 0.1000],
        [0.1900, 0.1500, 0.1700]])
张量除100:tensor([[-17, -10, -10],
        [-19, -15, -17]])


In [34]:
# 点乘运算
data1 = torch.tensor([[1, 2], [3, 4]])
data2 = torch.tensor([[5, 6], [7, 8]])
# 第一种方式
data = torch.mul(data1, data2)
print(data)
# 第二种方式
data = data1 * data2
print(data)

tensor([[ 5, 12],
        [21, 32]])
tensor([[ 5, 12],
        [21, 32]])


In [35]:
# 矩阵乘法运算

# 点积运算
data1 = torch.tensor([[1, 2], [3, 4], [5, 6]])
data2 = torch.tensor([[5, 6], [7, 8]])
# 方式一:
data3 = data1 @ data2
print("data3-->", data3)
# 方式二:
data4 = torch.matmul(data1, data2)
print("data4-->", data4)

data3--> tensor([[19, 22],
        [43, 50],
        [67, 78]])
data4--> tensor([[19, 22],
        [43, 50],
        [67, 78]])


In [36]:
#  张量运算函数
'''
tensor.mean(dim=):平均值
tensor.sum(dim=):求和
tensor.min/max(dim=):最小值/最大值
tensor.pow(exponent=):幂次方 $$x^n$$
tensor.sqrt(dim=):平方根
tensor.exp():指数 $$e^x$$
tensor.log(dim=):对数 以e为底
dim=0按列计算,dim=1按行计算
'''

import torch

data = torch.randint(0, 10, [2, 3], dtype=torch.float64)
print(data)
# 1. 计算均值
# 注意: tensor 必须为 Float 或者 Double 类型
print(data.mean())
print(data.mean(dim=0))  # 按列计算均值
print(data.mean(dim=1))  # 按行计算均值
# 2. 计算总和
print(data.sum())
print(data.sum(dim=0))
print(data.sum(dim=1))
# 3. 计算平方
print(torch.pow(data, 2))
# 4. 计算平方根
print(data.sqrt())
# 5. 指数计算, e^n 次方
print(data.exp())
# 6. 对数计算
print(data.log())  # 以 e 为底
print(data.log2())
print(data.log10())


tensor([[3., 9., 4.],
        [0., 5., 7.]], dtype=torch.float64)
tensor(4.6667, dtype=torch.float64)
tensor([1.5000, 7.0000, 5.5000], dtype=torch.float64)
tensor([5.3333, 4.0000], dtype=torch.float64)
tensor(28., dtype=torch.float64)
tensor([ 3., 14., 11.], dtype=torch.float64)
tensor([16., 12.], dtype=torch.float64)
tensor([[ 9., 81., 16.],
        [ 0., 25., 49.]], dtype=torch.float64)
tensor([[1.7321, 3.0000, 2.0000],
        [0.0000, 2.2361, 2.6458]], dtype=torch.float64)
tensor([[2.0086e+01, 8.1031e+03, 5.4598e+01],
        [1.0000e+00, 1.4841e+02, 1.0966e+03]], dtype=torch.float64)
tensor([[1.0986, 2.1972, 1.3863],
        [  -inf, 1.6094, 1.9459]], dtype=torch.float64)
tensor([[1.5850, 3.1699, 2.0000],
        [  -inf, 2.3219, 2.8074]], dtype=torch.float64)
tensor([[0.4771, 0.9542, 0.6021],
        [  -inf, 0.6990, 0.8451]], dtype=torch.float64)


In [184]:
# 张量索引操作
# 我们在操作张量时，经常需要去获取某些元素就进行处理或者修改操作，在这里我们需要了解在torch中的索引操作。

import torch

# 随机生成数据 data[开始行(可省略默认：0): 行步长(可省略默认：1): 结束行(可省略默认：shape), 开始列(可省略默认：0): 列步长(可省略默认：1): 结束列(可省略默认：shape)]
data = torch.randint(0 ,10, [4, 5])
print(f'随机生成张量：{data}')


# 1、简单行列索引
print(f'行索引：{data[0]}')
print(f'列索引：{data[:, 0]}')

# 2、列表索引
print(f'返回(0, 1)和(1, 2)对应位置数据：{data[[0, 1], [1, 2]]}')
print(f'返回0、1行的1、2列共4个元素：{data[:2, 1:3]}')
print(f'返回0、1行的1、2列共4个元素：{data[[[0], [1]], [1,2]]}')

# 3、范围索引
print(f'前三行前两列数据：{data[:3, :2]}')
print(f'第二行到最后的前两列数据：{data[2:, :2]}')

# 4、布尔索引
print(f'第三列大于5的行数据:{data[:, :3][data[:, :3] > 5]}')
print(f'第二行大于5的数据：{data[:, [1]][data[:, [1]] > 5]}')
print(f'第二行大于5的数据：{data[:, 1:2][data[:, 1:2] > 5]}')

# 5、多维索引
data = torch.randint(0, 10, [3, 4, 5])
print(f'随机生成三维数据：{data}')
print(f'获取0轴上第一个数据：{data[0, :, :]}')
print(f'获取0轴上第一个数据：{data[[0]]}')

print(f'获取0轴上第一个数据：{data[[1]]}')
print(f'获取1轴上第一个数据：{data[: , 0, :]}')
print(f'获取2轴上第一个数据：{data[: , :, 0]}')

随机生成张量：tensor([[9, 3, 4, 0, 5],
        [1, 4, 0, 7, 4],
        [2, 1, 7, 6, 4],
        [2, 4, 1, 8, 2]])
行索引：tensor([9, 3, 4, 0, 5])
列索引：tensor([9, 1, 2, 2])
返回(0, 1)和(1, 2)对应位置数据：tensor([3, 0])
返回0、1行的1、2列共4个元素：tensor([[3, 4],
        [4, 0]])
返回0、1行的1、2列共4个元素：tensor([[3, 4],
        [4, 0]])
前三行前两列数据：tensor([[9, 3],
        [1, 4],
        [2, 1]])
第二行到最后的前两列数据：tensor([[2, 1],
        [2, 4]])
第三列大于5的行数据:tensor([9, 7])
第二行大于5的数据：tensor([], dtype=torch.int64)
第二行大于5的数据：tensor([], dtype=torch.int64)
随机生成三维数据：tensor([[[1, 9, 4, 5, 4],
         [2, 8, 9, 7, 9],
         [3, 0, 3, 1, 1],
         [4, 6, 2, 4, 8]],

        [[8, 7, 4, 2, 8],
         [7, 2, 0, 7, 6],
         [2, 8, 9, 2, 8],
         [7, 8, 0, 3, 8]],

        [[9, 9, 5, 4, 9],
         [9, 8, 5, 3, 5],
         [4, 2, 5, 4, 6],
         [0, 9, 6, 4, 9]]])
获取0轴上第一个数据：tensor([[1, 9, 4, 5, 4],
        [2, 8, 9, 7, 9],
        [3, 0, 3, 1, 1],
        [4, 6, 2, 4, 8]])
获取0轴上第一个数据：tensor([[[1, 9, 4, 5, 4],
         [2, 8, 

In [185]:
# 张量形状操作
import torch

data = torch.tensor([[10, 20, 30], [40, 50, 60]])
# 1. 使用 shape 属性或者 size 方法都可以获得张量的形状
print(data.shape, data.shape[0], data.shape[1])
print(data.size(), data.size(0), data.size(1))

# 2. 使用 reshape 函数修改张量形状
new_data = data.reshape(1, 6)
print(new_data.shape)


torch.Size([2, 3]) 2 3
torch.Size([2, 3]) 2 3
torch.Size([1, 6])


In [199]:
data = torch.randint(0, 10, [3, 4, 5, 6 ,7])
print(f'张量：{data}')
print(f'张量形状：{data.shape}')
print(f'张量形状：{data.shape[0]}')
print(f'张量形状：{data.shape[1]}')
print(f'张量形状：{data.shape[2]}')
print(f'张量形状：{data.shape[3]}')

print(f'张量形状：{data.size(0)}')
print(f'张量形状：{data.size(1)}')
print(f'张量形状：{data.size(2)}')
print(f'张量形状：{data.size(3)}')

# 2. 使用 reshape 函数修改张量形状
reshape_data = data.reshape([3, 2, 5, 6, 14])
print(f'张量修改形状(总数不变)：{reshape_data}')
print(reshape_data.shape)

张量：tensor([[[[[5, 6, 0,  ..., 7, 0, 1],
           [3, 9, 1,  ..., 7, 6, 5],
           [9, 8, 5,  ..., 2, 4, 4],
           [3, 3, 4,  ..., 2, 8, 7],
           [1, 3, 9,  ..., 5, 1, 7],
           [6, 0, 0,  ..., 3, 7, 0]],

          [[6, 7, 2,  ..., 1, 3, 6],
           [7, 4, 5,  ..., 8, 8, 4],
           [6, 2, 4,  ..., 4, 2, 3],
           [8, 0, 9,  ..., 4, 6, 0],
           [2, 5, 0,  ..., 7, 5, 0],
           [4, 7, 9,  ..., 4, 1, 7]],

          [[0, 4, 7,  ..., 2, 9, 3],
           [4, 9, 1,  ..., 7, 7, 8],
           [1, 6, 3,  ..., 8, 5, 2],
           [9, 8, 8,  ..., 7, 7, 0],
           [2, 3, 2,  ..., 0, 5, 0],
           [2, 4, 7,  ..., 2, 1, 7]],

          [[0, 2, 4,  ..., 8, 4, 9],
           [6, 6, 8,  ..., 4, 4, 6],
           [4, 3, 1,  ..., 8, 0, 1],
           [3, 2, 3,  ..., 8, 1, 5],
           [5, 8, 5,  ..., 4, 2, 5],
           [1, 3, 5,  ..., 2, 9, 9]],

          [[6, 5, 7,  ..., 9, 2, 2],
           [3, 8, 3,  ..., 4, 9, 2],
           [3, 4, 3,  ..., 

In [195]:
import torch

data = torch.tensor([[10, 20, 30], [40, 50, 60]])
# 1. 使用 shape 属性或者 size 方法都可以获得张量的形状
print(data.shape, data.shape[0], data.shape[1])
print(data.size(), data.size(0), data.size(1))

# 2. 使用 reshape 函数修改张量形状
new_data = data.reshape(1, 6)
print(new_data.shape)

torch.Size([2, 3]) 2 3
torch.Size([2, 3]) 2 3
torch.Size([1, 6])


随机生成三维数据：tensor([[[[0]]]])
